################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.c 

OBJS += \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.o 

C_DEPS += \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/CMSIS/DSP/Source/StatisticsFunctions/%.o Drivers/CMSIS/DSP/Source/StatisticsFunctions/%.su Drivers/CMSIS/DSP/Source/StatisticsFunctions/%.cyclo: ../Drivers/CMSIS/DSP/Source/StatisticsFunctions/%.c Drivers/CMSIS/DSP/Source/StatisticsFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U575xx -DTX_INCLUDE_USER_DEFINE_FILE -DTX_SINGLE_MODE_NON_SECURE=1 -DNX_INCLUDE_USER_DEFINE_FILE -c -I../Core/Inc -IC:/Users/ethan/STM32Cube/Repository/STM32Cube_FW_U5_V1.7.0/Drivers/STM32U5xx_HAL_Driver/Inc -IC:/Users/ethan/STM32Cube/Repository/STM32Cube_FW_U5_V1.7.0/Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -IC:/Users/ethan/STM32Cube/Repository/STM32Cube_FW_U5_V1.7.0/Drivers/CMSIS/Device/ST/STM32U5xx/Include -IC:/Users/ethan/STM32Cube/Repository/STM32Cube_FW_U5_V1.7.0/Drivers/CMSIS/Include -I"C:/Users/ethan/STM32CubeIDE/workspace_1.17.0/SchoolZoneAlert_Final/My_Workspace/Inc" -I"C:/Users/ethan/STM32CubeIDE/workspace_1.17.0/SchoolZoneAlert_Final/Middlewares/Third_Party/NetXDuo/common/inc" -I"C:/Users/ethan/STM32CubeIDE/workspace_1.17.0/SchoolZoneAlert_Final/Middlewares/Third_Party/ThreadX/common/inc" -I"C:/Users/ethan/STM32CubeIDE/workspace_1.17.0/SchoolZoneAlert_Final/Middlewares/Third_Party/ThreadX/ports/cortex_m33/gnu/inc" -I"C:/Users/ethan/STM32CubeIDE/workspace_1.17.0/SchoolZoneAlert_Final/Middlewares/Third_Party/NetXDuo/ports/cortex_m33/gnu" -I"C:/Users/ethan/STM32CubeIDE/workspace_1.17.0/SchoolZoneAlert_Final/Middlewares/Third_Party/NetXDuo/ports/cortex_m33/gnu/inc" -I"C:/Users/ethan/STM32CubeIDE/workspace_1.17.0/SchoolZoneAlert_Final/Middlewares/Third_Party/NetXDuo/common/drivers/ethernet" -I../AZURE_RTOS/App -IC:/Users/ethan/STM32Cube/Repository/STM32Cube_FW_U5_V1.7.0/Middlewares/ST/threadx/common/inc -IC:/Users/ethan/STM32Cube/Repository/STM32Cube_FW_U5_V1.7.0/Middlewares/ST/threadx/ports/cortex_m33/gnu/inc -I../NetXDuo/App -I../NetXDuo/Target -IC:/Users/ethan/STM32Cube/Repository/STM32Cube_FW_U5_V1.7.0/Middlewares/ST/netxduo/common/inc -IC:/Users/ethan/STM32Cube/Repository/STM32Cube_FW_U5_V1.7.0/Middlewares/ST/netxduo/ports/cortex_m33/gnu/inc -I"C:/Users/ethan/STM32CubeIDE/workspace_1.17.0/SchoolZoneAlert_Final/Middlewares/Third_Party/NetXDuo/common/drivers/template/ethernet" -I"C:/Users/ethan/STM32CubeIDE/workspace_1.17.0/SchoolZoneAlert_Final/Drivers/CMSIS" -I"C:/Users/ethan/STM32CubeIDE/workspace_1.17.0/SchoolZoneAlert_Final/Drivers/CMSIS/Include" -I"C:/Users/ethan/STM32CubeIDE/workspace_1.17.0/SchoolZoneAlert_Final/NetXDuo" -I"C:/Users/ethan/STM32CubeIDE/workspace_1.17.0/SchoolZoneAlert_Final/Middlewares/Third_Party/NetXDuo/common" -I"C:/Users/ethan/STM32CubeIDE/workspace_1.17.0/SchoolZoneAlert_Final/Middlewares/Third_Party" -I"C:/Users/ethan/STM32CubeIDE/workspace_1.17.0/SchoolZoneAlert_Final/AZURE_RTOS" -I"C:/Users/ethan/STM32CubeIDE/workspace_1.17.0/SchoolZoneAlert_Final/Drivers/STM32U5xx_HAL_Driver" -I"C:/Users/ethan/STM32CubeIDE/workspace_1.17.0/SchoolZoneAlert_Final/Drivers/STM32U5xx_HAL_Driver/Src" -I"C:/Users/ethan/STM32CubeIDE/workspace_1.17.0/SchoolZoneAlert_Final/Drivers/STM32U5xx_HAL_Driver/Inc" -I../Drivers/STM32U5xx_HAL_Driver/Inc -I../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I"C:/Users/ethan/STM32Cube/Repository/STM32Cube_FW_U5_V1.7.0/Drivers/STM32U5xx_HAL_Driver" -I"C:/Users/ethan/STM32Cube/Repository/STM32Cube_FW_U5_V1.7.0/Drivers/CMSIS/Include" -I"C:/Users/ethan/STM32CubeIDE/workspace_1.17.0/SchoolZoneAlert_Final/Drivers/CMSIS/DSP/Include" -I"C:/Users/ethan/STM32CubeIDE/workspace_1.17.0/SchoolZoneAlert_Final/Drivers/CMSIS/DSP/Include/dsp" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-StatisticsFunctions

clean-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-StatisticsFunctions:
	-$(RM) ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d
	-$(RM) ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.su
	-$(RM) ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.su
	-$(RM) ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.o
	-$(RM) ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.su

.PHONY: clean-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-StatisticsFunctions

